Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/05/2017
Var
// Seção de Declarações das variáveis 



Inicio
leia(s)
escolha s
        caso 1
             escreval("domingo")
        caso 2
             escreval("terça")

// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo